export const projects = [
    {
        id: 'bind',
        index: 1,
        name: 'Bind',
        subname: 'Bind - Connecting You with the World',
        thumbnail: '/img/projects/bind.png',
        desc: 'A social media platform designed to bring people closer together.',
        shortDesc:
            'A social media platform designed to bring people closer together.',
        tools: ['Next JS', 'Tailwind CSS', 'Laravel'],
        year: '24',
        projectLink: 'https://bind-app-demo.vercel.app',
        githubLink: 'https://github.com/BimaPn/bind-server',
        collaborators: ['Bima PN'],
        client: '-',
        role: 'Backend Developer',
        isHighlighted: true,
    },
    {
        id: 'jitu',
        name: 'Jitu!',
        index: 2,
        subname: 'Jitu! - Menuju Keunggulan, Dengan Kedisiplinan!',
        thumbnail: '/img/projects/jitu.png',
        desc: 'A simple system to help schools track and manage student violations.',
        shortDesc:
            'A simple system to help schools track and manage student violations.',
        tools: ['Laravel', 'React JS', 'Tailwind CSS'],
        year: '24',
        projectLink: '#',
        githubLink: 'https://github.com/fabianazh/jitu',
        collaborators: ['-'],
        client: '-',
        role: 'Full Stack Developer',
        isHighlighted: true,
    },
    {
        id: 'tictactest',
        name: 'TicTacTest',
        index: 3,
        subname: 'TicTacTest - Your Classic Tic Tac Toe Playground!',
        thumbnail: '/img/projects/tictactest.png',
        desc: 'TicTacTest is your go-to destination for a classic game of Tic Tac Toe in its purest form.',
        shortDesc: 'Your go-to destination for a classic game of TicTacToe.',
        tools: ['React JS', 'Tailwind CSS', 'Chakra UI'],
        year: '23',
        projectLink: 'https://fabianazh.github.io/tic-tac-test',
        githubLink: 'https://github.com/fabianazh/tic-tac-test',
        collaborators: ['-'],
        client: '-',
        role: 'Frontend Developer',
        isHighlighted: false,
    },
    {
        id: 'zufar-portfolio',
        index: 4,
        name: 'Portfolio Web',
        subname: `Zufar's Portfolio`,
        thumbnail: '/img/projects/portfolio.png',
        desc: 'A professional web portfolio I designed, featuring a clean and engaging interface.',
        shortDesc:
            'A professional web portfolio I designed, featuring a clean and engaging interface.',
        tools: ['Next JS', 'Tailwind CSS', 'Firebase'],
        year: '24',
        projectLink: 'https://zufarms.vercel.app',
        githubLink: 'https://fabianazh.github.io/portfolio-zufar',
        collaborators: ['-'],
        client: '-',
        role: 'Full Stack Developer',
        isHighlighted: true,
    },
    {
        id: 'quranku',
        index: 5,
        name: 'QuranKu',
        subname: 'QuranKu - Your Portable Portal to the Quranverse',
        thumbnail: '/img/projects/quranku.png',
        desc: 'A modern and accessible Quran web application designed to provide users with a seamless reading experience anywhere, anytime.',
        shortDesc:
            'A modern and accessible Quran web application designed to provide users with a seamless reading experience anywhere, anytime.',
        tools: ['Next JS', 'Tailwind CSS', 'Chakra UI'],
        year: '23',
        projectLink: 'https://quranku-one.vercel.app',
        githubLink: 'https://github.com/fabianazh/quranku',
        collaborators: ['-'],
        client: '-',
        role: 'Frontend Developer',
        isHighlighted: true,
    },
    {
        id: 'starbucks-clone',
        index: 6,
        name: 'Starbucks Clone',
        subname: 'Starbucks Clone',
        thumbnail: '/img/projects/starbucks.png',
        desc: 'A landing page from popular coffee shop.',
        shortDesc: 'A landing page from popular coffee shop.',
        tools: ['React JS', 'Tailwind CSS', 'Chakra UI'],
        year: '23',
        projectLink: 'https://fabianazh.github.io/starbucks-clone',
        githubLink: 'https://github.com/fabianazh/quranku',
        collaborators: ['-'],
        client: '-',
        role: 'Frontend Developer',
        isHighlighted: false,
    },
]
