export const projects = [
    {
        id: 'bind',
        index: 1,
        name: { en: 'Bind', id: 'Bind' },
        subname: {
            en: 'Bind - Connecting You with the World',
            id: 'Bind - Connecting You with the World',
        },
        thumbnail: '/img/projects/bind.png',
        desktopViewImage: '/img/projects/bind.png',
        tabletViewImage: '/img/projects/bind.png',
        mobileViewImage: '/img/projects/bind.png',
        desc: {
            en: 'Bind is a social media platform designed to foster connections by combining shared interests with interactive features. It facilitates seamless communication through messaging, posting, and group interactions, making it a powerful tool for building communities and enhancing online engagement. Its intuitive design and diverse communication options cater to users seeking meaningful interactions and active social networking.',
            id: 'Bind adalah platform media sosial yang dirancang untuk membangun koneksi dengan menggabungkan minat bersama dengan fitur interaktif. Platform ini memfasilitasi komunikasi yang lancar melalui pesan, posting, dan interaksi grup, menjadikannya alat yang kuat untuk membangun komunitas dan meningkatkan keterlibatan online. Desainnya yang intuitif dan berbagai opsi komunikasi melayani pengguna yang mencari interaksi bermakna dan jejaring sosial yang aktif.',
        },
        shortDesc: {
            en: 'A social media platform designed to bring people closer together.',
            id: 'Platform media sosial yang dirancang untuk mendekatkan orang satu sama lain.',
        },
        tools: ['Next JS', 'Tailwind CSS', 'Laravel'],
        year: '24',
        projectLink: 'https://bind-app-demo.vercel.app',
        githubLink: 'https://github.com/BimaPn/bind-server',
        collaborators: ['Bima PN'],
        role: 'Backend Developer',
        isHighlighted: true,
        photos: [],
        created_at: '2025-01-02T12:11:18.456Z',
        keywords: [
            'Bind',
            'Social Media',
            'Fabian Azhar projects',
            'Next JS',
            'Laravel',
            'Tailwind CSS',
            'Backend Development',
            'Web App',
            'Collaborative Platform',
            'Connecting People',
            'Networking',
            'Communication',
            'Community',
            'Interactive Features',
            'Online Presence',
            'User Engagement',
            'Social Networking',
            'Modern Web App',
            'Digital Interaction',
            'Real-time Communication',
            'Social Connectivity',
        ],
    },
    {
        id: 'jitu',
        name: { en: 'Jitu!', id: 'Jitu!' },
        index: 2,
        subname: {
            en: 'Jitu! - Menuju Keunggulan, Dengan Kedisiplinan!',
            id: 'Jitu! - Menuju Keunggulan, Dengan Kedisiplinan!',
        },
        thumbnail: '/img/projects/jitu.png',
        desktopViewImage: '/img/projects/jitu.png',
        tabletViewImage: '/img/projects/jitu.png',
        mobileViewImage: '/img/projects/jitu.png',
        desc: {
            en: 'Jitu! is a system tailored for educational institutions to streamline student behavior management. It simplifies tracking and recording of student violations, enhancing school discipline with a user-friendly interface and detailed reporting. Designed to boost administrative efficiency, Jitu! supports schools in maintaining discipline standards and improving academic environments through effective behavior management.',
            id: 'Jitu! adalah sistem yang dirancang untuk institusi pendidikan guna menyederhanakan manajemen perilaku siswa. Sistem ini mempermudah pelacakan dan pencatatan pelanggaran siswa, meningkatkan disiplin sekolah dengan antarmuka yang ramah pengguna dan pelaporan yang terperinci. Dirancang untuk meningkatkan efisiensi administrasi, Jitu! mendukung sekolah dalam mempertahankan standar disiplin dan memperbaiki lingkungan akademik melalui manajemen perilaku yang efektif.',
        },
        shortDesc: {
            en: 'A simple system to help schools track and manage student violations.',
            id: 'Sistem sederhana untuk membantu sekolah memantau dan mengelola pelanggaran siswa.',
        },
        tools: ['Laravel', 'React JS', 'Tailwind CSS'],
        year: '24',
        projectLink: '#',
        githubLink: 'https://github.com/fabianazh/jitu',
        collaborators: ['-'],
        role: 'Full Stack Developer',
        isHighlighted: true,
        photos: [],
        created_at: '2025-01-02T12:11:18.456Z',
        keywords: [
            'Jitu!',
            'School Management',
            'Fabian Azhar projects',
            'Laravel',
            'React JS',
            'Tailwind CSS',
            'Discipline Tracking',
            'Student Violations',
            'Full Stack Development',
            'Efficient Management',
            'Educational Tools',
            'Behavior Monitoring',
            'Digital Discipline',
            'School Efficiency',
            'Classroom Management',
            'Student Record',
            'Violation Management',
            'Educational Technology',
            'Web Solutions for Schools',
            'Discipline Systems',
        ],
    },
    {
        id: 'tictactest',
        name: { en: 'TicTacTest', id: 'TicTacTest' },
        index: 3,
        subname: {
            en: 'TicTacTest - Your Classic Tic Tac Toe Playground!',
            id: 'TicTacTest - Your Classic Tic Tac Toe Playground!',
        },
        thumbnail: '/img/projects/tictactest.png',
        desktopViewImage: '/img/projects/tictactest.png',
        tabletViewImage: '/img/projects/tictactest.png',
        mobileViewImage: '/img/projects/tictactest.png',
        desc: {
            en: 'TicTacTest brings a classic game of Tic Tac Toe online with a sleek, modern interface. This game offers an easy-to-access platform for players to engage in strategic gameplay and relive the nostalgia of a classic game. Built with current web technologies, it provides a smooth and responsive experience across different devices, making it ideal for quick play and casual entertainment.',
            id: 'TicTacTest menghadirkan permainan klasik Tic Tac Toe secara online dengan antarmuka yang ramping dan modern. Permainan ini menawarkan platform yang mudah diakses bagi para pemain untuk terlibat dalam gameplay strategis dan menghidupkan kembali nostalgia dari permainan klasik. Dibangun dengan teknologi web terkini, TicTacTest menyediakan pengalaman yang mulus dan responsif di berbagai perangkat, menjadikannya ideal untuk permainan cepat dan hiburan santai.',
        },
        shortDesc: {
            en: 'Your go-to destination for a classic game of TicTacToe.',
            id: 'Destinasi utama Anda untuk permainan klasik TicTacToe.',
        },
        tools: ['React JS', 'Tailwind CSS', 'Chakra UI'],
        year: '23',
        projectLink: 'https://fabianazh.github.io/tic-tac-test',
        githubLink: 'https://github.com/fabianazh/tic-tac-test',
        collaborators: ['-'],
        role: 'Frontend Developer',
        isHighlighted: false,
        photos: [],
        created_at: '2025-01-02T12:11:18.456Z',
        keywords: [
            'TicTacTest',
            'Tic Tac Toe',
            'Fabian Azhar projects',
            'React JS',
            'Tailwind CSS',
            'Chakra UI',
            'Classic Games',
            'Browser Games',
            'Web Development',
            'Game Development',
            'Frontend Development',
            'Interactive Games',
            'Strategic Gameplay',
            'Pure Gaming Experience',
            'Simple Games',
            'Casual Games',
            'Entertainment',
            'Online Games',
            'JavaScript Games',
            'Playground',
        ],
    },
    {
        id: 'zufar-portfolio',
        index: 4,
        name: { en: `Zufar's Portfolio`, id: 'Portfolio Zufar' },
        subname: { en: `Zufar's Portfolio`, id: 'Portfolio Zufar' },
        thumbnail: '/img/projects/portfolio.png',
        desktopViewImage: '/img/projects/portfolio.png',
        tabletViewImage: '/img/projects/portfolio.png',
        mobileViewImage: '/img/projects/portfolio.png',
        desc: {
            en: 'This professional web portfolio is crafted to effectively display a wide range of projects and skills. It features a user-friendly design with sections for project details, skill highlights, and contact information. The modern and engaging layout enhances personal branding and communicates professional expertise, providing visitors with a comprehensive view of achievements and capabilities.',
            id: 'Portofolio web profesional ini dirancang untuk menampilkan berbagai proyek dan keterampilan secara efektif. Portofolio ini menampilkan desain yang ramah pengguna dengan bagian untuk detail proyek, sorotan keterampilan, dan informasi kontak. Tata letak yang modern dan menarik meningkatkan personal branding dan mengkomunikasikan keahlian profesional, memberikan pengunjung pandangan komprehensif tentang pencapaian dan kemampuan.',
        },
        shortDesc: {
            en: 'A professional web portfolio I designed, featuring a clean and engaging interface.',
            id: 'Portofolio web profesional yang saya rancang, menampilkan antarmuka yang bersih dan menarik.',
        },
        tools: ['Next JS', 'Tailwind CSS', 'Firebase'],
        year: '24',
        projectLink: 'https://zufarms.vercel.app',
        githubLink: 'https://fabianazh.github.io/portfolio-zufar',
        collaborators: ['-'],
        role: 'Full Stack Developer',
        isHighlighted: true,
        photos: [],
        created_at: '2025-01-02T12:11:18.456Z',
        keywords: [
            'Portfolio Web',
            'Web Portfolio',
            'Fabian Azhar projects',
            'Next JS',
            'Tailwind CSS',
            'Firebase',
            'Professional Portfolio',
            'Showcase Projects',
            'Web Design',
            'Full Stack Development',
            'Digital Resume',
            'Online Presence',
            'Clean Interface',
            'Engaging Design',
            'Personal Branding',
            'Project Showcase',
            'Skill Showcase',
            'Responsive Design',
            'Modern Web Portfolio',
            'UI/UX Design',
        ],
    },
    {
        id: 'quranku',
        index: 5,
        name: { en: 'QuranKu', id: 'QuranKu' },
        subname: {
            en: 'QuranKu - Your Portable Portal to the Quranverse',
            id: 'QuranKu - Your Portable Portal to the Quranverse',
        },
        thumbnail: '/img/projects/quranku.png',
        desktopViewImage: '/img/projects/quranku.png',
        tabletViewImage: '/img/projects/quranku.png',
        mobileViewImage: '/img/projects/quranku.png',
        desc: {
            en: 'QuranKu offers an accessible and user-friendly platform for engaging with the Quran. This web application is designed for seamless reading and interaction, making it easier for users to access and study religious texts. Featuring a responsive design and modern web technologies, QuranKu ensures a smooth experience across various devices, enhancing spiritual reflection and study.',
            id: 'QuranKu menawarkan platform yang mudah diakses dan ramah pengguna untuk berinteraksi dengan Al-Quran. Aplikasi web ini dirancang untuk membaca dan berinteraksi dengan lancar, memudahkan pengguna mengakses dan mempelajari teks-teks keagamaan. Dengan desain responsif dan teknologi web modern, QuranKu memastikan pengalaman yang mulus di berbagai perangkat, meningkatkan refleksi spiritual dan studi.',
        },
        shortDesc: {
            en: 'A modern and accessible Quran web application designed to provide users with a seamless reading experience anywhere, anytime.',
            id: 'Aplikasi web Quran yang modern dan mudah diakses, dirancang untuk memberikan pengalaman membaca yang mulus di mana saja, kapan saja.',
        },
        tools: ['Next JS', 'Tailwind CSS', 'Chakra UI'],
        year: '23',
        projectLink: 'https://quranku-one.vercel.app',
        githubLink: 'https://github.com/fabianazh/quranku',
        collaborators: ['-'],
        role: 'Frontend Developer',
        isHighlighted: true,
        photos: [],
        created_at: '2025-01-02T12:11:18.456Z',
        keywords: [
            'QuranKu',
            'Quran Web App',
            'Fabian Azhar projects',
            'Next JS',
            'Tailwind CSS',
            'Chakra UI',
            'Religious App',
            'Seamless Reading',
            'Islamic App',
            'Accessible Quran',
            'Modern Web App',
            'Frontend Development',
            'Spirituality',
            'Faith Technology',
            'Digital Quran',
            'User-Friendly Interface',
            'Anywhere Reading',
            'Mobile Accessibility',
            'Religious Studies',
            'Web App Development',
        ],
    },
    // {
    //     id: 'starbucks-clone',
    //     index: 6,
    //     name:{en: 'Starbucks Clone',id: 'Starbucks Clone' },
    //     subname: {en:'Starbucks Clone',id:'Starbucks Clone' },
    //     thumbnail: '/img/projects/starbucks.png',
    //     desktopViewImage: '/img/projects/starbucks.png',
    //     tabletViewImage: '/img/projects/starbucks.png',
    //     mobileViewImage: '/img/projects/starbucks.png',
    //     desc: {
    //         en: 'The Starbucks Clone project replicates the visual and interactive elements of Starbucks’ website. It provides a responsive and engaging landing page that captures the brand’s essence, showcasing skills in UI/UX design and web development. This clone project demonstrates the ability to recreate well-known brand experiences with attention to detail and responsive design principles.',
    //         id: 'Proyek Starbucks Clone meniru elemen visual dan interaktif dari situs web Starbucks. Proyek ini menyediakan halaman arahan yang responsif dan menarik yang menangkap esensi merek, menampilkan keterampilan dalam desain UI/UX dan pengembangan web. Proyek kloning ini menunjukkan kemampuan untuk menciptakan kembali pengalaman merek yang terkenal dengan perhatian terhadap detail dan prinsip desain responsif.',
    //     },
    //     shortDesc: {
    //         en: 'A landing page replicating the visual design and interactive experience of Starbucks.',
    //         id: 'Halaman situs yang meniru desain visual dan pengalaman interaktif Starbucks.',
    //     },
    //     tools: ['React JS', 'Tailwind CSS'],
    //     year: '23',
    //     projectLink: 'https://starbucks-clone-one.vercel.app',
    //     githubLink: 'https://github.com/fabianazh/starbucks-clone',
    //     collaborators: ['-'],
    //     role: 'Frontend Developer',
    //     isHighlighted: false,
    //     photos: [],
    //     created_at: '2025-01-02T12:11:18.456Z',
    //     keywords: [
    //         'Starbucks Clone',
    //         'Web Clone',
    //         'Fabian Azhar projects',
    //         'React JS',
    //         'Tailwind CSS',
    //         'Landing Page Design',
    //         'UI/UX Design',
    //         'Responsive Design',
    //         'Brand Replication',
    //         'Website Recreation',
    //         'Web Development',
    //         'Front-End Skills',
    //         'Interactive Design',
    //         'Digital Experience',
    //         'Brand Experience',
    //         'Web Design Project',
    //         'E-commerce UI',
    //         'Online Branding',
    //         'Responsive Landing Page',
    //         'Brand Clone',
    //     ],
    // },
    {
        id: 'grand-boulevard',
        index: 6,
        name: { en: 'Grand Boulevard', id: 'Grand Boulevard' },
        subname: {
            en: 'Grand Boulevard - A Taste of Elegance',
            id: 'Grand Boulevard - A Taste of Elegance',
        },
        thumbnail: '/img/projects/grand-boulevard.png',
        desktopViewImage: '/img/projects/grand-boulevard.png',
        tabletViewImage: '/img/projects/grand-boulevard.png',
        mobileViewImage: '/img/projects/grand-boulevard.png',
        desc: {
            en: 'Grand Boulevard is an exquisite landing page designed for a high-end restaurant, embodying elegance and sophistication. The page reflects the luxurious atmosphere of the restaurant, providing visitors with a seamless and visually appealing experience. With its refined design and modern web technologies, Grand Boulevard effectively communicates the essence of fine dining, attracting discerning customers and enhancing the restaurant’s online presence.',
            id: 'Grand Boulevard adalah halaman situs yang indah yang dirancang untuk restoran kelas atas, mewujudkan keanggunan dan kecanggihan. Halaman ini mencerminkan suasana mewah restoran, memberikan pengunjung pengalaman yang mulus dan menarik secara visual. Dengan desainnya yang halus dan teknologi web modern, Grand Boulevard secara efektif mengkomunikasikan esensi bersantap mewah, menarik pelanggan yang cermat dan meningkatkan kehadiran online restoran.',
        },
        shortDesc: {
            en: 'A landing page crafted for a luxurious dining experience.',
            id: 'Halaman situs yang dirancang untuk pengalaman restoran mewah.',
        },
        tools: ['Next JS', 'Tailwind CSS', 'Framer Motion'],
        year: '23',
        projectLink: 'https://grand-boulevard.vercel.app/',
        githubLink: 'https://github.com/fabianazh/grand-boulevard',
        collaborators: ['-'],
        role: 'Frontend Developer',
        isHighlighted: false,
        photos: [],
        created_at: '2025-01-02T12:11:18.456Z',
        keywords: [
            'Grand Boulevard',
            'Restaurant Landing Page',
            'Fabian Azhar projects',
            'Next JS',
            'Tailwind CSS',
            'Framer Motion',
            'Fine Dining',
            'Frontend Development',
            'Web Design',
            'Luxury Experience',
            'Modern Web App',
            'UI/UX Design',
            'Interactive Experience',
            'Digital Branding',
            'High-End Web Design',
            'Responsive Design',
            'Visual Appeal',
            'Restaurant Website',
            'Web Development',
        ],
    },
]
